### ISSUE TITLE
consistent behavior of compute on nrows

### ISSUE THREAD

**Issue by pratapvardhan** [blaze/blaze#1434]
Computing `nrows` expression for csv file and sqlite file gives different `type`. For csv files, type is int ax expected. But, for sqlite (probably for other sql too?) it's a sqlalchemy Select object.

```python
In [91]: bz.__version__
Out[91]: '0.9.0'

In [92]: data = bz.Data('iris.csv')                     # csv file

In [93]: bz.compute(data.nrows)
Out[93]: 150

In [94]: type(bz.compute(data.nrows))
Out[94]: int

In [95]: data = bz.Data('sqlite:///iris.db::iris')       # sqlite file

In [96]: bz.compute(data.nrows)
Out[96]: <sqlalchemy.sql.selectable.Select at 0x1775eb3da0; Select object>

In [97]: type(bz.compute(data.nrows))
Out[97]: sqlalchemy.sql.selectable.Select

In [98]: data.nrows
Out[98]: 150
```

as an alternative to `bz.compute`, could probably use `bz.into(int, data.nrows)` instead.

Is this behavior of `bz.compute` on `data.nrows` expected?

**Comment by postelrich** [comment]
this duplicates #1411 and fixed in #1417

**Comment by pratapvardhan** [comment]
Thanks @postelrich However it works out for `return_type=int` but doesn't "reach out" for `return_type=float` in case of `sql`
```python
In [21]: bz.__version__
Out[21]: '0.9.1+83.gc96748e'

In [22]: data_csv = bz.Data('blaze/examples/data/iris.csv')

In [23]: data_sql = bz.Data('sqlite:///blaze/examples/data/iris.db::iris')

In [24]: bz.compute(data_csv.nrows, return_type=int)
Out[24]: 150

In [25]: bz.compute(data_sql.nrows, return_type=int)
Out[25]: 150

In [26]: bz.compute(data_sql.nrows, return_type=float)
Out[26]: 150

In [27]: bz.compute(data_csv.nrows, return_type=float)
.......showing last few lines
..\networkx\algorithms\shortest_paths\weighted.py in dijkstra_path(G, source, target, weight)
     81     except KeyError:
     82         raise nx.NetworkXNoPath(
---> 83             "node %s not reachable from %s" % (source, target))
     84
     85

NetworkXNoPath: node <class 'int'> not reachable from <class 'float'>
```
I'm thinking, functionally this should extend to coerce any type?

**Comment by postelrich** [comment]
What is with the networkx error? I don't believe that is a dependency of blaze.  See if you still get an error with a clean environment and fresh a terminal.

**Comment by pratapvardhan** [comment]
blaze uses odo for type conversion which uses networkx internally.

This error persists with 
```python
In [9]: bz.__version__
Out[9]: '0.9.1+168.g5622ba4.dirty'
```

additionally, now even,  `bz.compute(data_sql.nrows, return_type=float)` is failing error message similar to #1463

**Comment by postelrich** [comment]
return_type was added in version 0.10

**Comment by pratapvardhan** [comment]
Thanks @postelrich for pointing to version. But issue still persists with bleeding edge version `'0.10.0rc4+0.g6961844.dirty'`
